# Generated by Django 5.2.14 on 2026-05-28 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=200, verbose_name='پسورد')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن')),
                ('traffic_limit', models.BigIntegerField(default=0, help_text='0 = نامحدود', verbose_name='حد ترافیک (بایت)')),
                ('traffic_used', models.BigIntegerField(default=0, verbose_name='ترافیک مصرفی (بایت)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('servers', models.ManyToManyField(blank=True, to='servers.server', verbose_name='سرورها')),
            ],
            options={
                'verbose_name': 'کلاینت',
                'verbose_name_plural': 'کلاینت\u200cها',
            },
        ),
    ]
