# Generated by Django 5.2.14 on 2026-05-30 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='توکن'),
        ),
    ]
