# Generated by Django 5.2.14 on 2026-05-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرور')),
                ('host', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('port', models.PositiveIntegerField(default=22, verbose_name='پورت SSH')),
                ('ssh_user', models.CharField(default='root', max_length=50, verbose_name='یوزر SSH')),
                ('ssh_password', models.CharField(max_length=200, verbose_name='پسورد SSH')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سرور',
                'verbose_name_plural': 'سرورها',
            },
        ),
    ]
