# Generated by Django 5.2.14 on 2026-05-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='host_key',
            field=models.CharField(default='', max_length=256, verbose_name='نام سرور'),
            preserve_default=False,
        ),
    ]
