# Generated by Django 5.2.14 on 2026-05-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='host_key',
            field=models.CharField(max_length=256, verbose_name='کلید هاست'),
        ),
    ]
