# Generated by Django 5.2.14 on 2026-06-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_alter_server_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(max_length=100, verbose_name='آدرس IP'),
        ),
    ]
