# Generated by Django 5.2.14 on 2026-06-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_alter_server_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.GenericIPAddressField(verbose_name='آدرس IP'),
        ),
    ]
